#version 450
#include "default_header.glsl"

layout(constant_id = 1) const uint BUCKETS = 42;

layout(binding = 0) buffer partitionOffsetsB { uint partitionOffsets[]; };
layout(binding = 1) buffer bucketOffsetsB { uint bucketOffsets[]; };

void main() {
    uint offset = 0;
    if (wID>0) {
        offset = partitionOffsets[wID - 1];
    }
    uint arrayOffset = wID * BUCKETS;
    for (uint i = lID + arrayOffset; i < BUCKETS + arrayOffset; i+=wSize) {
        bucketOffsets[i] += offset;
    }
}